### ISSUE TITLE
Assertion failure is hard to read

### ISSUE THREAD

**Issue by dagguh** [Cutter72/NordeaTaskTDD#4]
Currently (as of acd4c652233b9a6c43cd215fb1ba98d9f6e4a153), `XmlConverterImplTest` fails with a huge assertion error. It's hard to find the difference, even with IntelliJ's aid.

Both expected and actual XMLs are single-line. If we make them multiline, then the diff should be much clearer. Moreover, we could use AssertJ excellent assertions, like [`hasSameContentAs(File)`](https://static.javadoc.io/org.assertj/assertj-core/3.13.2/org/assertj/core/api/AbstractFileAssert.html#hasSameContentAs(java.io.File)). AssertJ produces fantasyically readable assertion messages.

**Comment by Cutter72** [comment]
I had the same feeling about that.

**Comment by Cutter72** [comment]
Done.
